<?php
/**
 * Copyright © magebig.com - All rights reserved.
 * See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Wishlist\Block\Catalog\Product\View\AddTo\Wishlist $block */
?>
<?php 
$helper = $this->helper('Ranosys\MainWarehouseApi\Helper\Data');
$value = $helper->isloggedin();
?>
<?php if ($block->isWishListAllowed()) : ?>
	<?php if ($value=="false"): ?>
		<button type="button"
       class="action towishlist mb-tooltip"
       title="<?= $block->escapeHtml(__('Add to Wish List')) ?>"><a href="/customer/account/login/"><span class="mbi mbi-heart"></span></a></button>
    <?php else: ?>
    <button type="button"
       class="action towishlist mb-tooltip"
       data-post='<?= /* @noEscape */ $block->getWishlistParams() ?>'
       data-action="add-to-wishlist" title="<?= $block->escapeHtml(__('Add to Wish List')) ?>"><span class="mbi mbi-heart"></span></button>
    <?php endif; ?>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "body": {
            "addToWishlist": <?= /* @noEscape */ $block->getWishlistOptionsJson() ?>
        }
    }
</script>
