<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_Checkout
 */
?>
<?php
/** @var \Magento\Checkout\Block\Onepage $block */
/** @var \Amasty\Checkout\Helper\Onepage $helper */
/** @var \Amasty\Checkout\Model\Optimization\BundleService $bundleService */
$helper = $block->getData('amcheckout_helper');
$bundleService = $block->getData('bundleService');
$design = $helper->isModernCheckoutDesign() ? 'modern' : 'classic';
$layout = $helper->getDesignLayout();
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();        
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$store_id = $storeManager->getStore()->getStoreId();
$base_url = $storeManager->getStore()->getBaseUrl();
?>

<div id="checkout"
     data-bind="scope:'checkout'"
     class="checkout-container am-checkout -<?= /* @noEscape */ $design?> -layout-<?= /* @noEscape */ $layout?>"
     data-amcheckout-js="checkout">
    <div class="checkout-header">
        <div class="secondary col-md-6">
            <a href="<?php /* @escapeNotVerified */
            echo $block->getUrl('checkout/cart/'); ?>" class="action primary"><span><?php /* @escapeNotVerified */
                    echo __('Back to Shopping Cart') ?></span></a>
            <h1 class="title"><?= __($block->escapeHtml($helper->getTitle())) ?></h1>
            <!--<div class="description"><?= /* @noEscape */ __($helper->getDescription()) ?></div>-->
        </div>
        <div class = "col-md-6">
            <?php if($store_id == 1){ ?>
                <a href="<?php echo $base_url; ?>"><img class="img-fluid" src="/media/logo/stores/1/Norway.png" alt="" width="341" height="27"></a>
                <script>
                    window.onload = function() {
                        setInterval(function(){
                        jQuery('input[name="telephone"]').attr('maxlength',8);
                    }, 500);
                    };


                </script>
            <?php } elseif($store_id == 11){ ?>
                <a href="<?php echo $base_url; ?>"><img class="img-fluid" src="/media/logo/stores/11/boat-parts.se.png" alt="" width="341" height="27"></a>
            <?php } elseif($store_id == 12){?>
                <a href="<?php echo $base_url; ?>"><img class="img-fluid" src="/media/logo/stores/12/boat-parts.dk.png" alt="" width="341" height="27"></a>
            <?php } elseif($store_id == 12){?>
                <a href="<?php echo $base_url; ?>"><img class="img-fluid" src="/media/logo/stores/13/Europe.png" alt="" width="341" height="27"></a>
            <?php } else { ?>
                <a href="<?php echo $base_url; ?>"><img class="img-fluid" src="/media/logo/stores/13/Europe.png" alt="" width="341" height="27"></a>
            <?php } ?>
        </div>
        
    </div>

    <div id="checkout-loader" data-role="checkout-loader" class="loading-mask" data-mage-init='{"checkoutLoader": {}}'>
        <div class="loader">
            <img src="<?=
            /* @noEscape */ $block->getViewFileUrl('images/loader-1.gif'); ?>"
                 alt="<?= $block->escapeHtml(__('Loading...')); ?>"
                 style="position: absolute;">
        </div>
    </div>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#checkout": {
                "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout();?>
            }
        }
    </script>
    <script>
        require.config({
            config: {
                mixins: {
                    'Magento_Ui/js/view/messages': {
                        'Amasty_Checkout/js/view/messages-mixin': true
                    }
                }
            }
        });
        window.checkoutConfig = <?= /* @escapeNotVerified */ \Zend_Json::encode($block->getCheckoutConfig()); ?>;
        // Create aliases for customer.js model from customer module
        window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
        window.customerData = window.checkoutConfig.customerData;
        window.checkoutDesign = "<?= $helper->isModernCheckoutDesign() ? 'modern' : 'classic'?>";
        window.checkoutLayout = "<?= $block->escapeHtml($helper->getLayoutTemplate())?>";
    </script>
    <script>
        require([
            'mage/url',
            'Magento_Ui/js/block-loader'
        ], function(url, blockLoader) {
            blockLoader("<?=
                /* @noEscape */ $block->getViewFileUrl('images/loader-1.gif'); ?>");
            return url.setBaseUrl('<?= /* @noEscape */ $block->getBaseUrl();?>');
        });
    </script>
<?php if ($bundleService->canCollectBundle()): ?>
    <script>
        require([
            'rjsResolver',
            'underscore',
            '<?= \Amasty\Checkout\Model\Optimization\BundleService::COLLECT_SCRIPT_PATH ?>',
        ], function(requireResolver, _, createBundle) {
            requireResolver(_.debounce(createBundle, 1000));
        });
    </script>
<?php endif; ?>

    <?php if ($helper->isAddressSuggestionEnabled() && ($apiKey = $helper->getGoogleMapsKey())): ?>
    <script>
        window.amasty_checkout_regions = <?= /* @noEscape */ $helper->getRegionsJson() ?>;
        function amasty_checkout_gmaps_init() {
            require(['Amasty_Checkout/js/autocomplete'], function (autocomplete) {
                autocomplete.isReady(true);
            });
        }
    </script>
    <script
        src="https://maps.googleapis.com/maps/api/js?key=<?=
        /* @noEscape */ $block->stripTags($apiKey);?>&libraries=places&callback=amasty_checkout_gmaps_init"
        async defer>
    </script>
    <?php endif ?>
</div>
<style>
    .checkout-header .action {
    margin-bottom: 20px;
    }
    .checkout-index-index .checkout-header {
    margin-top: 0;
    }
</style>
