<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php /** @var $block \Magento\Sales\Block\Order\Info */ ?>
<?php $_order = $block->getOrder() ?>
<?php $var= $block->getOrder()->getIncrementId();
$image= $this->helper('Ranosys\MainWarehouseApi\Helper\Barcode')->generateBarcode($var);
   ?>
   <div class="barcode">
        <img src="<?php echo $image; ?>" class="barcode-image">
    </div>

<span class="pdf-heading"><?php echo $this->helper('Ranosys\MainWarehouseApi\Helper\Data')->getConfig('boatparts_address/general/pdf_heading'); ?></span>

<div class="block block-order-details-view">
         <div class="block-content">
            <div class="customer-info box">
                <strong class="box-title"><span><?= $block->escapeHtml(__('Customer:')) ?></span></strong>
                <div class="box-content">
                    <address><?= /* @noEscape */ $block->getFormattedAddress($_order->getBillingAddress()) ?></address>
                </div>
                
            </div>
            <div class="box box-order-method">
                <span class="order-id"><strong><?= $block->escapeHtml(__('Order #:')) ?></strong><?php echo $var; ?></span> 
                <div class="order-date">
                <strong><?= $block->escapeHtml(__('Date:')) ?></strong><?= $block->escapeHtml(__(' %1', '<span>' . $block->formatDate($block->getOrder()->getCreatedAt(), \IntlDateFormatter::LONG) . '</span>'), ['span', 'date']) ?>
                </div>
                <div class="box-order-billing-method flex-order">
                    <strong class="box-title">
                        <span><?= $block->escapeHtml(__('Payment Method:')) ?></span>
                    </strong>
                    <div class="box-content">
                        <?php  $payment = $_order->getPayment();
                    $method = $payment->getMethodInstance();
                    $methodTitle = $method->getTitle();
                    echo $methodTitle; ?>
                    </div>
                </div>
                <span class="order-Status"><strong><?= $block->escapeHtml(__('Order Status:')) ?></strong><?= $block->escapeHtml($block->getOrder()->getStatusLabel()) ?></span>
                <?php if (!$_order->getIsVirtual()) : ?>
                    <div class="box-order-shipping-method flex-order">
                        <strong class="box-title">
                            <span><?= $block->escapeHtml(__('Shipping Method:')) ?></span>
                        </strong>
                        <div class="box-content">
                        <?php if ($_order->getShippingDescription()) : ?>
                            <?= $block->escapeHtml($_order->getShippingDescription()) ?>
                        <?php else : ?>
                            <?= $block->escapeHtml(__('No shipping information available')) ?>
                        <?php endif; ?>
                        </div>
                    </div>
                <?php endif; ?>
                <div class="customer-email"><strong class="customer-email"><span><?= $block->escapeHtml(__('Email: ')) ?></span></strong><?= $block->escapeHtml($block->getOrder()->getCustomerEmail()) ?></div>
            </div>
        <?php if (!$_order->getIsVirtual()) : ?>
            <div class="box box-order-shipping-address">
                <strong class="box-title"><span><?= $block->escapeHtml(__('Delivery Address:')) ?></span></strong>
                <div class="box-content">
                    <address><?= /* @noEscape */ $block->getFormattedAddress($_order->getShippingAddress()) ?></address>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>
<style type="text/css">
.page-print .logo {
    float: right;
}
.page-print {
    font-size: 13px;
    font-family: 'Helvetica', 'Arial', sans-serif;
}
.account .column.main .block:not(.widget) .box-title > span {
    font-weight: bold;
}
.block-order-details-view .block-content .box strong {
    font-weight: bold;
}
.page-print .payment-method.checkmemo .content {
    display: none;
}
.page-print .box-order-billing-method .content {
    display: none;
}
.page-print .box.box-order-shipping-address {
    clear: left !important;
}
.page-print address {
    margin-bottom: 10px;
}
.flex-order {
    display: grid;
    grid-template-columns: auto 1fr;
    align-items: center;
}

.flex-order .box-content {
    padding-left: 5px !important;
    font-size: 12px;
}
.flex-order .box-content dl {
    margin-bottom: 0;
}
.page-print .order-details-items .table-order-items .product-item-name {
    font-size: 14px;
}

.page-print .order-details-items .table-wrapper .qty {
    text-align: center !important;
}
</style>