<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Sales\Block\Order\Info */ ?>

<div class="block-title">
        <strong><?= $block->escapeHtml(__('Custom information')) ?></strong>
    </div>
<style type="text/css">
.modal-inner-content {
    display: none;
}
.page-print {
    font-size: 14px;
    font-family: 'Helvetica', 'Arial', sans-serif;
}
.block-title {
    position: absolute;
    top: 25px;
    font-size: 20px;
}
.block-title strong {
    font-weight: 500;
}
.page-title {
	font-size: 15px;
}
.barcode  {
	height: 80px;
    display: block;
    text-align: left;
    object-fit: cover;
}
.barcode-image {
    width: 202px;
    height: 50px;
    position: relative;
    left: -20px;
}
.pdf-heading {
	height: 80px;
}
.page-main .block.block-order-details-view {
    margin-bottom: 10px;
    margin-top: 20px;
}
span.order-Status strong, span.order-id strong, .order-date > span:first-child {
    font-weight: 500;
}

.block-order-details-view .block-content .box, .pge-print address {
    margin-bottom: 0;
}


.block-order-details-view .block-content .box * {padding: 0;}

.block-order-details-view .block-content .box .box-title {
    margin-bottom: 0 !important;
}
.order-details-items.ordered #my-orders-table thead th.name, .order-details-items.ordered #my-orders-table thead th.sku {
    text-align: left;
}
.order-details-items.ordered #my-orders-table thead th.price, .order-details-items.ordered #my-orders-table thead th.subtotal{
    text-align: left;
}
.order-details-items.ordered #my-orders-table td.price, .order-details-items.ordered #my-orders-table td.subtotal{
    text-align: left;
}
.page-print .page-title-wrapper{ margin-top: 0;}
@media only screen and (max-width: 767px){
    .page-title-wrapper .block-title {
        top: 0;
    }
    .page-print .logo img{float: none;}
    .page-print .logo {
        float: none;
    }
}
@media only screen and (min-width: 768px){
    .logo img {
        max-width: 100%;
        height: auto;
        width: 40%;
        float: right;
        position: relative;
        top: 70px;
    }
}
</style>

