<?php
/**
 * Copyright © magebig.com - All rights reserved.
 * See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var \Magento\Wishlist\Block\Link $block */
//$wishlistHelper = $this->helper('Ranosys\MainWarehouseApi\Helper\Data');
//$count = $wishlistHelper->getWishlistCount();
?>
<div id ="wishlist-counter" class="col col-wishlist d-none d-md-block">
    <div class="wishlist-topbar">
        <li style="list-style: none;" class="link wishlist" data-bind="scope: 'wishlist'">
    <a <?= /* @noEscape */ $block->getLinkAttributes() ?> class="wishlist-icon link wishlist">
<i class="mbi mbi-heart" title="<?=__('Wishlist')?>"></i>
        <!-- ko if: wishlist().counter -->
        <span data-bind="text: wishlist().counter" class="counter-number qty"></span>
        <!-- /ko -->
    </a>
</li>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "wishlist": {
                        "component": "Magento_Wishlist/js/view/wishlist"
                    }
                }
            }
        }
    }

</script>
