<?php
//Work for Klarna Promotion on PDP page Start
$viewModel = $block->getLayout()->createBlock('Ranosys\Catalog\Block\Configration');
$currentStore = $viewModel->getCurrentStore();
$currentStoreId = $viewModel->getStoreId();
$klarnaPromotionEnable = $viewModel->getEnable($currentStoreId);
if ($klarnaPromotionEnable == 1) {
    $price = 0;
    $product = $block->getProduct();
    $productType = $product->getTypeId();
    $locale = "en-GB";
    if ($currentStore == "default") {
        $locale = "no-NO";
    }elseif($currentStore = "se"){
        $locale= "sv-SE";
    }
    if ($productType == 'bundle') {
        $price = (int) $product->getPriceInfo()->getPrice('final_price')->getMinimalPrice()->getValue();
    } elseif ($productType == 'configurable') {
        $price = (int) $product->getFinalPrice();
    } elseif ($productType == 'grouped') {
        $specialPrice = 0;
        $usedProds = $product->getTypeInstance(true)->getAssociatedProducts($product);
        foreach ($usedProds as $child) {
            if ($child->getId() != $product->getId()) {
                $specialPrice += $child->getFinalPrice();
            }
        }
        $price = (int) $specialPrice;
    } else {
        $price = (int) $product->getFinalPrice();
    }
}
//Work for Klarna Promotion on PDP page End
?>
<?php if ($block->getProductQtyIncrements()) : ?>
    <div class="product pricing">
        <?= $block->escapeHtml(__('%1 is available to buy in increments of %2', $block->getProductName(), $block->getProductQtyIncrements())) ?>
    </div>
<?php endif ?>
<!--Iframe For Klarna Promotion Text Start
Here $klarnaPromotionEnable Check backend configration Store-> configration->Ranosys->Kalrna
-->
<?php if ($klarnaPromotionEnable == 1) : ?>
    <!-- Placement v2 -->
    <klarna-placement
        data-key="credit-promotion-auto-size"
        data-locale="<?php echo $locale ?>"
        data-purchase-amount="<?php echo $price ?>"
        ></klarna-placement>
    <!-- end Placement -->
    <?php

 endif ?>