<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<?php if ($block->getCanViewOrder() && $block->getCanPrintOrder() && $block->orderDetails()=="PayPal Express Checkout"){?>
    <a href="<?php echo $this->getUrl('sales/product/invoice/') ?>"
       class="action print"
       target="_blank"
       rel="noopener">
        <?= $block->escapeHtml(__('Print invoice')) ?>
    </a>
    <?= $block->getChildHtml() ?>
<?php }
/*else { ?>
<a href="<?= $block->escapeUrl($block->getPrintUrl()) ?>"
       class="action print"
       target="_blank"
       rel="noopener">
        <?= $block->escapeHtml(__('Print receipt')) ?>
    </a>
    <?= $block->getChildHtml() ?>
<?php } */
?> 
<?php
$objectManager=\Magento\Framework\App\ObjectManager::getInstance();
if($block->orderDetails()=="SwedbankPay Payments") 
{
$orderId = $block->orderDetailsforpayex();
$order = $objectManager->create('\Magento\Sales\Model\Order')->load($orderId);
$emailSender = $objectManager->create('\Magento\Sales\Model\Order\Email\Sender\OrderSender');
$emailSender->send($order);
$block->sendEmailpayex();
}     
$storeManager=$objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$storeID=$storeManager->getStore()->getStoreId(); 
$resource = $objectManager->get('\Magento\Framework\App\ResourceConnection');
$connection = $resource->getConnection(\Magento\Framework\App\ResourceConnection::DEFAULT_CONNECTION);
$query = 'SELECT `template_id` FROM `eadesign_pdf_store` WHERE `store_id` = '. $storeID;
$values = $connection->fetchAll($query);
$templateId= $values[0]['template_id'];
$_SESSION['orderid'] = $block->getOrderId();
$_SESSION['template_id'] = $templateId;
?>
