<?php
$viewModel = $block->getLayout()->createBlock('Ranosys\WebsiteSwitcher\Block\StoreSwitchModel');
$viewModelStore = $block->getLayout()->createBlock('Magento\Store\Block\Switcher');
$websites = $viewModel->getWebsites();
$websiteid = $viewModel->getWebsite()->getWebsiteId();
$mbHelper       = $this->helper('MageBig\MbFrame\Helper\Data');
$logoSticky     = $mbHelper->getConfig('mbconfig/header/logo_sticky');
$pathLogo       = $mbHelper->getBaseMediaUrl() . 'wysiwyg/magebig/logo/';
$blockLogo      = $block->getLayout()->createBlock('Magento\Theme\Block\Html\Header\Logo');
$blockWelcome   = $block->getLayout()->createBlock('Magento\Theme\Block\Html\Header');
$blockCustomer  = $block->getLayout()->createBlock('Magento\Customer\Block\Account\Customer');
//$wishlistHelper = $this->helper('Magento\Wishlist\Helper\Data');
$menuLayout     = $mbHelper->getConfig('mbconfig/header/menu_layout');
$klarnaPdpBlock = $block->getLayout()->createBlock('Ranosys\Catalog\Block\Configration');
?>
<?php
    echo $this->getLayout()
        ->createBlock(\Magento\Cms\Block\Block::class)
        ->setBlockId('mv05-fixed-block') 
        ->toHtml();
?>
<div class="header-top-inner">
    <div class="container">
        <div class="row align-items-center header-top-row">
            <div class="d-none d-md-block col-sm-3 col-lg-5">
                <div class="welcome"><?= $blockWelcome->getWelcome() ?></div>
            </div>
            <div class="col-12 col-md-9 col-lg-7">
                <div class="row align-items-center justify-content-end top-link-wrap">
                    <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('top-links')->toHtml(); ?>
                    <?= $this->getChildHtml('currency') ?>
                    <?= $this->getChildHtml('store_language') ?>
                    <div class="language-topbar switcher language switcher-language" id="switcher-store">
    <div class="actions dropdown options switcher-options lang-curr">
        <?php foreach ($websites as $website): ?>
            <?php if ($websiteid == $website->getId()): ?>
                <div class="action toggle switcher-trigger"
                     role="button"
                     tabindex="0"
                     data-mage-init='{"dropdown":{}}'
                     data-toggle="dropdown"
                     data-trigger-keypress-button="true"
                     id="switcher-store-trigger">
                    <span class="title">
                        <span class="lang-flag <?= $website->getCode(); ?>"></span>
                        <span class="lang-name"><?php echo $block->escapeHtml(__('Boatparts '.$website->getDefaultStore()->getName())) ?></span>
                        <i class="mbi mbi-ios-arrow-down"></i>
                    </span>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
        <div class="lang-list">
            <ul class="dropdown switcher-dropdown" data-target="dropdown">
                <?php foreach ($websites as $website): ?>
                    <?php if (!($websiteid == $website->getId()) && $website->getCode() != "forhandler" ): ?>
                        <li class="switcher-option view">
                            <a href='#' data-post='<?php echo $viewModelStore->getTargetStorePostData($website->getDefaultStore()) ?>'>
                            <span class="lang-flag <?= $website->getCode(); ?>"></span>
                            <span class="lang-name"><?= $block->escapeHtml(__('Boatparts '.$website->getDefaultStore()->getName())) ?></span>
                            </a>
                        </li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
</div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="header-main-content sticky-menu">
    <div class="container">
        <div class="header-main-inner <?php if ($menuLayout == 'horizontal') : ?>header-horizontal<?php endif;?>">
            <div class="row align-items-center header-maininner-row">
                <div class="col-12 col-md-3 col-lg-3 col-logo">
                    <div class="menu-logo">
                        <?= $this->getChildHtml('logo') ?>
                        <div class="icon-top-mobile">
                            <div class="mobile-video-icon">
                                    <?php
                                echo $this->getLayout()
                                    ->createBlock(\Magento\Cms\Block\Block::class)
                                    ->setBlockId('boatparts-video-link') 
                                    ->toHtml();
                                ?>
                            </div>
                            <div class="minicart-action">
                                <a class="action showcart" href="<?= $block->getUrl('checkout/cart') ?>"
                                   data-bind="scope: 'minicart_content'">
                                    <i class="mbi mbi-bag2"></i>
                                    <span class="counter qty empty"
                                          data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
                                    <span class="counter-number"><!-- ko text: getCartParam('summary_count') --><!-- /ko --></span>
                                    <span class="counter-label">
                                    <!-- ko if: getCartParam('summary_count') -->
                                        <!-- ko text: getCartParam('summary_count') --><!-- /ko -->
                                        <!-- ko i18n: 'items' --><!-- /ko -->
                                        <!-- /ko -->
                                    </span>
                                </span>
                                </a>
                            </div>
                            <?= $this->getChildHtml('wishlist_icon') ?>
                        </div>
                    </div>
                    <?= $this->getChildHtml('smartmenu.topnav') ?>
                </div>
                <div class="col-md-5 col-lg-5 col-xl-6 col-search">
                    <div class="top-search-wrap mfp-with-anim">
                    <p class="search-top-text"><?= $block->escapeHtml(__('Are you looking for (starter Yamaha or steering kit) or enter the original part number'))?></p>
                        <?= $this->getChildHtml('topSearch') ?>
                    </div>
                </div>
                <div class="col-12 col-md-4 col-lg-4 col-xl-3 col-btn-actions-desktop d-none d-md-block">
                    <div class="header-content-action row no-gutters">
                        <div class="col col-video">
                            <?php
                            echo $this->getLayout()
                                ->createBlock(\Magento\Cms\Block\Block::class)
                                ->setBlockId('boatparts-video-link') 
                                ->toHtml();
                            ?>
                        </div>
                        <?= $this->getChildHtml('wishlist_icon') ?>
                        <?= $this->getChildHtml('minicart') ?>
                            <?php /* ?>
                            <span class="counter qty">
                                <span class="cart-label"> - </span>
                                <span class="subtotal-top" data-bind="scope: 'ajaxcart_content'">
                                    <!-- ko ifnot: getCartParam('subtotal') -->
                                    <span class="price-zero"><?= $this->helper('Magento\Framework\Pricing\Helper\Data')->currency(number_format(0, 2), true, false); ?></span>
                                    <!-- /ko -->
                                    <span class="price-label" data-bind="html: getCartParam('subtotal')"></span>
                                </span>
                            </span>
                            */ ?>
                        <div class="user-topbar col">
                            <i class="mbi mbi-user"></i>
                            <?= $this->getChildHtml('header.links') ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="header-menu-content d-none d-md-block">
    <div class="container">
        <div class="menu-container">
            <?php if ($menuLayout == 'vertical') : ?>
            <div class="row align-items-center">
                <div class="col-3 d-none d-md-block">
                </div>
                <div class="col-9 col-md-9 col-lg-6 d-none d-md-block">
                    <div class="horizontal-menu-wrap"><?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('horizontal-menu')->toHtml(); ?></div>
                </div>
                <div class="col-12 col-md-3 d-none d-lg-block"><?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('hotline')->toHtml(); ?></div>
            </div>
            <?php else: ?>
            <div class="row align-items-center">
                <div class="col-12">
                    <?= $this->getChildHtml('smartmenu.topnav-hori') ?>
                </div>
            </div>
            <?php endif; ?>
        </div>
    </div>
</div>
<div class="d-block d-md-none col-btn-actions">
    <div class="header-content-action row no-gutters">
        <div class="btn-nav-mobile col">
            <button type="button" class="btn-nav mb-toggle-switch mb-toggle-switch__htx"><span></span></button>
        </div>
        <div class="btn-search-mobile col">
            <i class="mbi mbi-magnifier"></i>
        </div>
        <div class="col col-home">
            <a href="<?= $block->getBaseUrl() ?>" class="go-home"><i class="mbi mbi-home3"></i></a>
        </div>

        <div class="col">
            <div class="minicart-action">
                <a class="action showcart" href="<?= $block->getUrl('checkout/cart') ?>" data-bind="scope: 'minicart_content'">
                    <i class="mbi mbi-bag2"></i>
                    <span class="counter qty empty" data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
                        <span class="counter-number"><!-- ko text: getCartParam('summary_count') -->0<!-- /ko --></span>
                        <span class="counter-label">
                        <!-- ko if: getCartParam('summary_count') --><!-- /ko -->
                        </span>
                    </span>
                </a>
            </div>
        </div>

        <div class="user-topbar col">
            <i class="mbi mbi-user"></i>
        </div>
    </div>
</div>
<script>
require(['jquery', 'jquery/ui'], function($){
    $(document).ready(function() {
    remoClerkNofromFilters();

//Remove No after selecting filter
        $('#clerk-search-filters').on('click', function(){
          remoClerkNofromFilters();
        });
    });

    function remoClerkNofromFilters(){
        setTimeout(function(){
        $('#clerk-search-filters').find('*[data-value="false"]').remove();
        $('#clerk-search-filters').find('*[data-value=""]').remove();
        $('#clerk-search-filters').find('*[data-value=undefined]').remove();
        $('.clerk-facet-group-facets').each(function(i, obj) {
            if($(this).children().length < 1){
                $(this).parent().remove();
            }
        });
        },1000);
    }
});
</script>
<!--Script For Klarna Promotion Text Start
Here $clientId Check backend configration Store-> configration->Ranosys->Kalrna
Client id genrated form playgroud on site message panel
-->
<?php
$storeId = $klarnaPdpBlock->getStoreId();
$clientId = $klarnaPdpBlock->getClientId($storeId);
$klarnaPromotionEnable = $klarnaPdpBlock->getEnable($storeId);
?>
<?php if(($klarnaPromotionEnable == 1) && (!empty($clientId))) :?>
<script
  async
  src="https://eu-library.playground.klarnaservices.com/lib.js"
  data-client-id="<?php echo $clientId;?>"
></script>
<?php endif ?>
<!--Script For Klarna Promotion Text End-->