<?php
/**
 * Copyright © magebig.com - All rights reserved.
 * See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */

$_mbHelper = $this->helper('MageBig\MbFrame\Helper\Data');
$id = $block->getGalleryId().$block->getProduct()->getId();
$images = $block->getGalleryImages()->getItems();
$imgCount = count($images);
$mainImage = current(array_filter($images, function ($img) use ($block) {
    return $block->isMainImage($img);
}));

if (!empty($images) && empty($mainImage)) {
    $mainImage = $block->getGalleryImages()->getFirstItem();
}

$helper = $this->helper('Magento\Catalog\Helper\Image');
$mainImageData = $mainImage ?
    $mainImage->getData('medium_image_url') :
    $helper->getDefaultPlaceholderUrl('image');
?>
<div class="gallery-placeholder _block-content-loading gallery-<?= $id; ?> <?php if ($imgCount) echo 'imgs'; ?>" data-gallery-role="gallery-placeholder">
    <img
        alt="main product photo"
        class="gallery-placeholder__image img-fluid"
        src="<?= /* @noEscape */ $mainImageData ?>"
    />
    <?php if ($imgCount) echo '<span class="thumb-pl"></span>'; ?>
</div>
<script type="text/x-magento-init">
    {
        ".gallery-<?= $id; ?>": {
            "mage/gallery/gallery": {
                "mixins":["magnifier/magnify"],
                "magnifierOpts": {"fullscreenzoom":"20","top":"0","left":"100%","width":"500","height":"500","eventType":"hover","enabled":true,"mode":"outside"},
                "data": <?= /* @escapeNotVerified */ $block->getGalleryImagesJson() ?>,
                "options": {
                    "thumbmargin": 10,
                    "thumbborderwidth": 1,
                    "autoplay": <?= (int)$_mbHelper->getConfig('mbconfig/product_view/gallery_autoplay') ?>,
                    "nav": "thumbs",
                    "loop": 1,
                    "keyboard": 1,
                    "arrows": 0,
                    "allowfullscreen": <?= (int)$_mbHelper->getConfig('mbconfig/product_view/allowfullscreen') ?>,
                    "showCaption": 0,
                    "width": <?= $block->getImageAttribute('product_page_image_medium', 'width') ?>,
                    "thumbwidth": <?= $block->getImageAttribute('product_page_image_small', 'width') ?>,
                    "thumbheight": <?= $block->getImageAttribute('product_page_image_small', 'height')
        ?: $block->getImageAttribute('product_page_image_small', 'width'); ?>,
                    "height": <?= $block->getImageAttribute('product_page_image_medium', 'height')
        ?: $block->getImageAttribute('product_page_image_medium', 'width'); ?>,
                    "transitionduration": <?= (int)$_mbHelper->getConfig('mbconfig/product_view/gallery_duration') ?>,
                    "transition": "<?= $_mbHelper->getConfig('mbconfig/product_view/gallery_effect') ?>",
                    "navarrows": 1,
                    "navtype": "slides",
                    "navdir": "<?= $_mbHelper->getConfig('mbconfig/product_view/nav_dir') ?>"
                },
                "fullscreen": {
                    "nav": "thumbs",
                    "loop": 1,
                    "navdir": "vertical",
                    "navarrows": 0,
                    "navtype": "slides",
                    "arrows": 1,
                    "showCaption": 1,
                    "transitionduration": 600,
                    "transition": "crossfade"
                },
                "breakpoints": {"mobile":{"conditions":{"max-width":"767px"},"options":{"options":{"nav":"thumbs","navdir":"horizontal"}}}}
            }
        }
    }
</script>
