<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Ranosys\Wishlist\Block\Cart\Item\Renderer\Actions\MoveToWishlist $block*/

/** @var \Magento\Wishlist\Helper\Data $helper */
$helper = $this->helper('Magento\Wishlist\Helper\Data');
?>
<!-- Allow in cart without customer logged in -->
<?php if ($helper->isAllow() && $block->isProductVisibleInSiteVisibility()): ?>
    <a href="#"
       data-post='<?php /* @escapeNotVerified */ echo $block->getMoveFromCartParamsCustom() ?>'
       class="use-ajax action towishlist action-towishlist"
    title="<?php echo __('Move to Wishlist') ?>">
        <span><?php /* @escapeNotVerified */ echo __('Move to Wishlist'); ?></span>
    </a>
<?php endif ?>
<style>
    .cart .towishlist.action-towishlist {
        padding-right: 30px;
    }
</style>