<div class="topbar-wrap">
    <div class="topbar-container">
        <div class="topbar-left">
            <ul>
                <li><a href="tel:+919928909310"><i class="fa-solid fa-phone"></i> +91 9928909310</a></li>
                <li><a href="mailto:khandalsushil82@gmail.com"><i class="fa-solid fa-envelope"></i> khandalsushil82@gmail.com</a></li>
            </ul>
            
        </div>
        <div class="topbar-right">
            <ul>
                <li><a href="#"><i class="fa-brands fa-facebook-f"></i> <?= __('Facebook'); ?></a></li>
                <li><a href="#"><i class="fa-brands fa-twitter"></i> <?= __('Twitter'); ?></a></li>
                <li><a href="#"><i class="fa-brands fa-linkedin-in"></i> <?= __('Linkedind'); ?></a></li>
            </ul>
        </div>
    </div>
    
</div>