<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>

<?php $_invoice = $block->getInvoice() ?>
<?php $_order   = $block->getOrder() ?>
<?php 
if (!empty($_order)):
    $storeCode = $_order->getStore()->getCode();?>
    <div class="barcodecell" style="text-align: left;">
        <barcode code="<?php echo $_order->getIncrementId()?>" type="C128A" class="barcode" style="margin-left: -12px; display:block;" />
        <p class="increment-id" style="letter-spacing: 14.5px; text-align: left;padding-top: -12px; padding-left:3px;display:block;"><?php echo $_order->getIncrementId() ?></p>
    </div>
    <?php if ($_invoice && $_order) : ?>
        <table class="email-items" style="width:100%; border-collapse: collapse;">
            <thead>
                <tr>
                    <th class="item-info" style="width: 180px; padding:5px; text-align: left;">
                        <?= $block->escapeHtml(__('Product')) ?>
                    </th>
                    <th class="item-sku" style="padding:5px; text-align: left;">
                        <?= $block->escapeHtml(__('SKU')) ?>
                    </th>
                    <th class="item-price" style="padding:5px; text-align: left;">
                        <?= $block->escapeHtml(__('Price')) ?>
                    </th>
                    <th class="item-qty" style="text-align: center; padding:5px;">
                        <?= $block->escapeHtml(__('Qty')) ?>
                    </th>
                    <?php if($storeCode == 'default'): ?>
                    <th class="item-country" style="padding:5px; text-align: left;">
                        <?= $block->escapeHtml(__('MVA')) ?>
                    </th>
                    <?php endif; ?>
                    <th class="item-country" style="text-align: left; padding:5px;">
                        <?= $block->escapeHtml(__('CoO')) ?>
                    </th>
                    <?php if($storeCode == 'default'): ?>
                    <th class="item-tollcode" style="text-align: left; padding:5px;">
                        <?= $block->escapeHtml(__('Toll kode')) ?>
                    </th>
                    <?php endif; ?>
                    <?php if($storeCode == 'se'): ?>
                    <th class="item-tollcode" style="text-align: left; padding:5px;">
                        <?= $block->escapeHtml(__('Tollkod')) ?>
                    </th>
                    <?php endif; ?>
                    <?php if($storeCode == 'dk'): ?>
                    <th class="item-tollcode" style="text-align: left; padding:5px;">
                        <?= $block->escapeHtml(__('Toll kode')) ?>
                    </th>
                    <?php endif; ?>
                    <?php if($storeCode == 'int'): ?>
                    <th class="item-tollcode" style="text-align: left; padding:5px;">
                        <?= $block->escapeHtml(__('Custom code')) ?>
                    </th>
                    <?php endif; ?>
                    <th class="item-subtotal">
                        <?= $block->escapeHtml(__('Subtotal')) ?>
                    </th>
                </tr>
            </thead>
            <?php foreach ($_invoice->getAllItems() as $_item) : ?>
                <?php if (!$_item->getOrderItem()->getParentItem()) : ?>
                    <tbody>
                        <?= $block->getItemHtml($_item) ?>
                    </tbody>
                <?php endif; ?>
            <?php endforeach; ?>
            <tfoot class="order-totals" colspan="7">
                <?= $block->getChildHtml('invoice_totals') ?>
            </tfoot>
        </table>
    <?php endif; ?>
<?php endif; ?>

<style>
.barcode-remove .barcodecell{
display:none;
}
  </style>